package octavo.cmsc124.lolcode_program.model;

public enum Token {
    VARIABLE_IDENTIFIER, FUNCTION_IDENTIFIER, LOOP_INDENTIFIER, NUMBR_LITERAL, NUMBAR_LITERAL, YARN_LITERAL,
    TROOF_LITERAL, TYPE_LITERAL,

    HAI, KTHXBYE, WAZZUP, BUHBYE, BTW, OBTW, TLDR, I_HAS_A, ITZ, R, SUM_OF, DIFF_OF, PRODUKT_OF, QUOSHUNT_OF, MOD_OF,
    BIGGR_OF, SMALLR_OF, BOTH_OF, EITHER_OF, WON_OF, NOT, ANY_OF, ALL_OF, BOTH_SAEM, DIFFRINT, SMOOSH, MAEK, A, IS_NOW_A,
    VISIBLE, GIMMEH, O_RLY, YA_RLY, MEBBE, NO_WAI, OIC, WTF, OMG, OMGWTF, IM_IN_YR, UPPIN, NERFIN, YR, TIL, WILE,
    IM_OUTTA_YR, HOW_IZ_I, IF_U_SAY_SO, GTFO, FOUND_YR, I_IZ, MKAY,

    STRING_DELIMETER, CODE_DELIMETER, VARIABLE_DECLARATION, VARIABLE_ASSIGNMENT, OUTPUT_KEYWORD,
}
